begin;

create table public.support_agents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Поддержка'
    check (char_length(display_name) between 1 and 80),
  created_at timestamptz not null default now()
);

create table public.support_conversations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_label text not null default 'Пользователь'
    check (char_length(owner_label) between 1 and 80),
  subject text not null default 'Новый вопрос'
    check (char_length(subject) between 1 and 120),
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index support_conversations_owner_idx
  on public.support_conversations (owner_id, updated_at desc);

create table public.support_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.support_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index support_messages_conversation_idx
  on public.support_messages (conversation_id, created_at);

create function public.is_support_agent()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.support_agents where user_id = auth.uid()
  );
$$;

revoke all on function public.is_support_agent() from public, anon;
grant execute on function public.is_support_agent() to authenticated;

alter table public.support_agents enable row level security;
alter table public.support_conversations enable row level security;
alter table public.support_messages enable row level security;

revoke all on public.support_agents from anon, authenticated;
revoke all on public.support_conversations from anon, authenticated;
revoke all on public.support_messages from anon, authenticated;
grant select on public.support_agents to authenticated;
grant select, insert, update on public.support_conversations to authenticated;
grant select, insert on public.support_messages to authenticated;
grant usage, select on sequence public.support_messages_id_seq to authenticated;

create policy support_agent_self_select on public.support_agents
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy support_conversation_select on public.support_conversations
  for select to authenticated
  using (
    owner_id = (select auth.uid()) or
    (select public.is_support_agent())
  );

create policy support_conversation_insert on public.support_conversations
  for insert to authenticated
  with check (owner_id = (select auth.uid()));

create policy support_conversation_agent_update on public.support_conversations
  for update to authenticated
  using ((select public.is_support_agent()))
  with check ((select public.is_support_agent()));

create policy support_message_select on public.support_messages
  for select to authenticated
  using (
    exists (
      select 1 from public.support_conversations conversation
      where conversation.id = conversation_id
        and (
          conversation.owner_id = (select auth.uid()) or
          (select public.is_support_agent())
        )
    )
  );

create policy support_message_insert on public.support_messages
  for insert to authenticated
  with check (
    sender_id = (select auth.uid()) and
    exists (
      select 1 from public.support_conversations conversation
      where conversation.id = conversation_id
        and conversation.status = 'open'
        and (
          conversation.owner_id = (select auth.uid()) or
          (select public.is_support_agent())
        )
    )
  );

create function public.touch_support_conversation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.support_conversations
    set updated_at = now()
    where id = new.conversation_id;
  return new;
end;
$$;

revoke all on function public.touch_support_conversation() from public, anon, authenticated;
create trigger support_message_touch_conversation
  after insert on public.support_messages
  for each row execute function public.touch_support_conversation();

alter publication supabase_realtime add table public.support_conversations;
alter publication supabase_realtime add table public.support_messages;

commit;
